### ISSUE TITLE
Allow benchmarking the driver rather than the runtime APIs

### ISSUE THREAD

**Issue by eyalroz** [harrism/cuda_event_benchmark#4]
I'm not entirely sure why this repository was created TBH, but - now that it exists, why not have it use either the runtime or the driver API?

**Comment by harrism** [comment]
I needed to benchmark the runtime API for CUDA events.  I will review any submitted PRs.

**Comment by harrism** [comment]
@eyalroz (or anyone for that matter) please feel free to reopen if you decide to submit a PR to implement this request.
