### ISSUE TITLE
Results Unit Inconsistency

### ISSUE THREAD

**Issue by Jacobfaib** [harrism/cuda_event_benchmark#5]
The results table has
```
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
BM_EventCreate<true>             782 us          782 us          923 items_per_second=1.27941M/s
BM_EventCreate<false>            422 us          422 us         1558 items_per_second=2.36813M/s
...
```
`us` indicates microseconds (and indeed the benchmark src has `...->Unit(benchmark::kMicrosecond)`). However `1 / 782e-6 = 1,278.77` implies that `782` is in nanoseconds (`1 / 782e-9 = 1,278,772`).

**Comment by harrism** [comment]
All of the timing and throughput calculations come from the Google Benchmark framework. The framework will run the benchmark multiple times to remove jitter. So they are trustworthy. 

The benchmark runs 1000 event operations per test in a loop. So the calculation is actually 1000 items / 782us == 1.279Mitems/s.
