### ISSUE TITLE
unit in benchmark report should be ns instead of us

### ISSUE THREAD

**Issue by ancile1** [harrism/cuda_event_benchmark#6]
benchmark report shows us, like:
`BM_EventCreate<true>             782 us          782 us          923 items_per_second=1.27941M/s`

This does not look like correct. 
1. 782 us is way too long for a CUDA event creation.
2. items_per_second=1.27941M/s -> 782 ns instead of us.
3. unit in ns matches the observation in nsight systems.

**Comment by ancile1** [comment]
Seems like we are reporting the total time for 1000 events, not the average time cost of each event:
`constexpr std::size_t events_size{1000};`

**Comment by harrism** [comment]
@ancile1 thanks for the report. I opened a PR to do one item per iteration. Have a look at https://github.com/harrism/cuda_event_benchmark/pull/7

Thanks!
Mark
